server:
  port: 8080

spring:
  application:
    name: api_gateway_service
  cloud:
    gateway:
      routes:
        - id : user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
        - id: board-service
          uri: lb://board-service
          predicates:
            - Path=/board/**
          filters:
            - RewritePath=/board/(?<segment>.*), /$\{segment}
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/category/**
          filters:
            - RewritePath=/category/(?<segment>.*), /$\{segment}
        - id: test-service
          uri: lb://test-service
          predicates:
            - Path=/test-service/**
          filters:
            - RewritePath=/test-service/(?<segment>.*), /$\{segment}
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comment/**
          filters:
            - RewritePath=/comment/(?<segment>.*), /$\{segment}
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allow-credentials : true
            allowed-origins:
              - 'http://localhost:3000'
              - 'https://weatherfit-frontend.vercel.app'
            allowed-headers:
              - '*'
            exposed-headers:
              - '*'
            allowed-methods:
              - POST
              - GET
              - PUT
              - PATCH
              - DELETE
              - OPTIONS

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

json-web-token:
  secret-key : 'kdt8ProjectWeatherfitSecretKeykdt8ProjectWeatherfitSecretKeykdt8ProjectWeatherfitSecretKey'
