spring:
  application:
    name: user-service
  profiles:
    include=oauth:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://weatherfit-user.cj2ysw4maina.ap-northeast-2.rds.amazonaws.com:3306/user_service
    username: wlfkrdl2
    password: gmltjd36!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 453423602833-7db2b1dbicre47rkcrpfgn20nd16l9rs.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
  mail:
    host: smtp.gmail.com
    port: 587
    username: wlfkrdl2@gmail.com
    password: hnqp swqi hxeh xjee
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 10MB
      
cloud:
  aws:
    credentials:
      access-key: AKIAVO5NLNBM3VISJPVS
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: heesung-s3
    stack:
      auto: false
      
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
    ip-address: 3.35.59.210
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://13.124.197.227:8761/eureka
server:
  port: 8080

